### PR TITLE
Added README.md

### LINKED ISSUE #1: Add freeradius docker image
Add a docker image with the following specifications:
OS: Ubuntu
Service/s: Freeradius (With pap, chap, mschap, and eap-md5)
Test coverage: Test commands to test pap, chap, mschap, and eap-md5 auth in the freeradius service

### PR DESCRIPTION
**Pull request by aditya274**
> Added README.md
> Closes #1.

### CODE REVIEW

**Comment by the-c0d3br34k3r** [comment]
@aditya274 
Please fix the mis-alignments in the README.
image

And also add the following message to your commit's description : "Closes #1."
The #1 refers to the issue for which this PR has been opened. And when this PR is merged, the issue is closed automatically if referenced as shown above.

**Review by the-c0d3br34k3r — APPROVED** [review]

**Comment by the-c0d3br34k3r** [comment]
@aditya274 The README looks good.
Please merge both the commits into a single commit with the following description.
>Added README.md
>
> Closes #1.

**Review by the-c0d3br34k3r — CHANGES_REQUESTED** [review]
@aditya274 The README looks good.
Please squash both the commits into a single commit with the following description.
>Added README.md
>
> Closes #1.

**Comment by aditya274** [comment]
Please review changes.

**Review by the-c0d3br34k3r — APPROVED** [review]

**Comment by the-c0d3br34k3r** [comment]
Changes have been approved. Thank you for your contribution @aditya274 !

**Pull request merged**
